# Generated by Django 2.2.5 on 2020-06-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='pan',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='age',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
